In [7]:
import requests
import pandas as pd
import time
from bs4 import BeautifulSoup

def get_soup(url):
    data = requests.get(url)
    return BeautifulSoup(data.text, 'html.parser')

def get_team_urls(standings_soup):
    standings_table = standings_soup.select('table.stats_table')[0]
    links = [l.get("href") for l in standings_table.find_all('a')]
    links = [l for l in links if '/squads/' in l]
    return [f"https://fbref.com{l}" for l in links]

def get_previous_season_url(standings_soup):
    previous_season = standings_soup.select("a.prev")[0].get("href")
    return f"https://fbref.com{previous_season}"

def get_team_data(team_url, year):
    team_name = team_url.split("/")[-1].replace("-Stats", "").replace("-", " ")
    data = requests.get(team_url)
    matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
    matches = matches[matches["Comp"] == "Premier League"]
    matches["Season"] = year
    matches["Team"] = team_name
    return matches

def scrape_premier_league_data(years):
    all_matches = []
    standings_url = "https://fbref.com/en/comps/9/2022-2023/2022-2023-Premier-League-Stats"

    for year in years:
        standings_soup = get_soup(standings_url)
        team_urls = get_team_urls(standings_soup)
        standings_url = get_previous_season_url(standings_soup)

        for team_url in team_urls:
            team_data = get_team_data(team_url, year)
            if team_data is not None:
                all_matches.append(team_data)
            time.sleep(3)

    return pd.concat(all_matches)

years = list(range(2022, 2018, -1))
all_matches_df = scrape_premier_league_data(years)

In [8]:
all_matches_df.reset_index(drop=True, inplace=True)  # Reset the index to provide automatic numbering
all_matches_df.to_csv('premier_league.csv')  # Save to CSV

In [9]:
import requests
import pandas as pd
import time
from bs4 import BeautifulSoup

def get_soup(url):
    data = requests.get(url)
    return BeautifulSoup(data.text, 'html.parser')

def get_team_urls(standings_soup):
    standings_table = standings_soup.select('table.stats_table')[0]
    links = [l.get("href") for l in standings_table.find_all('a')]
    links = [l for l in links if '/squads/' in l]
    return [f"https://fbref.com{l}" for l in links]

def get_previous_season_url(standings_soup):
    previous_season = standings_soup.select("a.prev")[0].get("href")
    return f"https://fbref.com{previous_season}"

def get_team_data(team_url, year):
    team_name = team_url.split("/")[-1].replace("-Stats", "").replace("-", " ")
    data = requests.get(team_url)

    standard_stats = pd.read_html(data.text, match="Standard Stats")[0]

    standard_stats["Season"] = year
    standard_stats["Team"] = team_name
    return standard_stats

def scrape_premier_league_data(years):
    all_matches = []
    standings_url = "https://fbref.com/en/comps/9/2022-2023/2022-2023-Premier-League-Stats"

    for year in years:
        standings_soup = get_soup(standings_url)
        team_urls = get_team_urls(standings_soup)
        standings_url = get_previous_season_url(standings_soup)

        for team_url in team_urls:
            team_data = get_team_data(team_url, year)
            if team_data is not None:
                all_matches.append(team_data)
            time.sleep(3)

    return pd.concat(all_matches)

years = list(range(2022, 2018, -1))
all_matches_df1 = scrape_premier_league_data(years)

In [37]:
all_matches_df1.columns = all_matches_df1.columns.droplevel(0)
all_matches_df1 = all_matches_df1[~all_matches_df1['Player'].isin(['Squad Total', 'Opponent Total'])]
all_matches_df1.head()

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,...,G+A-PK,xG,xAG,xG+xAG,npxG,npxG+xAG,Matches,Year,Year,MP
0,Ederson,br BRA,GK,28.0,35.0,35,3150.0,35.0,0.0,1.0,...,0.03,0.00,0.01,0.01,0.00,0.01,Matches,2022,Manchester City,NaN
1,Rodri,es ESP,MF,26.0,36.0,34,2911.0,32.3,2.0,6.0,...,0.25,0.14,0.13,0.27,0.14,0.27,Matches,2022,Manchester City,NaN
2,Erling Haaland,no NOR,FW,22.0,35.0,33,2769.0,30.8,36.0,8.0,...,1.20,0.92,0.17,1.10,0.75,0.92,Matches,2022,Manchester City,NaN
3,Kevin De Bruyne,be BEL,MF,31.0,32.0,28,2417.0,26.9,7.0,16.0,...,0.86,0.21,0.51,0.72,0.21,0.72,Matches,2022,Manchester City,NaN
4,İlkay Gündoğan,de GER,MF,31.0,31.0,27,2353.0,26.1,8.0,4.0,...,0.46,0.29,0.13,0.41,0.26,0.38,Matches,2022,Manchester City,NaN

In [26]:
all_matches_df1.reset_index(drop=True, inplace=True)  # Reset the index to provide automatic numbering
all_matches_df1.to_csv('Players.csv')  # Save to CSV

In [11]:
import requests
import pandas as pd
import time
from bs4 import BeautifulSoup

def get_soup(url):
    data = requests.get(url)
    return BeautifulSoup(data.text, 'html.parser')

def get_team_urls(standings_soup):
    standings_table = standings_soup.select('table.stats_table')[0]
    links = [l.get("href") for l in standings_table.find_all('a')]
    links = [l for l in links if '/squads/' in l]
    return [f"https://fbref.com{l}" for l in links]

def get_previous_season_url(standings_soup):
    previous_season = standings_soup.select("a.prev")[0].get("href")
    return f"https://fbref.com{previous_season}"

def get_team_data(team_url, year):
    team_name = team_url.split("/")[-1].replace("-Stats", "").replace("-", " ")
    data = requests.get(team_url)

    standard_stats = pd.read_html(data.text, match="Goalkeeping")[0]

    standard_stats["Season"] = year
    standard_stats["Team"] = team_name
    return standard_stats

def scrape_premier_league_data(years):
    all_matches = []
    standings_url = "https://fbref.com/en/comps/9/2022-2023/2022-2023-Premier-League-Stats"

    for year in years:
        standings_soup = get_soup(standings_url)
        team_urls = get_team_urls(standings_soup)
        standings_url = get_previous_season_url(standings_soup)

        for team_url in team_urls:
            team_data = get_team_data(team_url, year)
            if team_data is not None:
                all_matches.append(team_data)
            time.sleep(3)

    return pd.concat(all_matches)

years = list(range(2022, 2018, -1))
all_matches_df2 = scrape_premier_league_data(years)

In [24]:
all_matches_df2.columns = all_matches_df2.columns.droplevel(0)
all_matches_df2 = all_matches_df2[~all_matches_df2['Player'].isin(['Squad Total', 'Opponent Total'])]
all_matches_df2.head()

,Player,Nation,Pos,Age,MP,Starts,Min,90s,GA,GA90,...,CS,CS%,PKatt,PKA,PKsv,PKm,Save%,Matches,Year,Year
0,Ederson,br BRA,GK,28.0,35,35,3150,35.0,32.0,0.91,...,11.0,31.4,3.0,3.0,0.0,0.0,0.0,Matches,2022,Manchester City
1,Stefan Ortega,de GER,GK,29.0,3,3,270,3.0,1.0,0.33,...,2.0,66.7,0.0,0.0,0.0,0.0,NaN,Matches,2022,Manchester City
2,Aaron Ramsdale,eng ENG,GK,24.0,38,38,3420,38.0,43.0,1.13,...,14.0,36.8,5.0,3.0,0.0,2.0,0.0,Matches,2022,Arsenal
3,David de Gea,es ESP,GK,31.0,38,38,3420,38.0,43.0,1.13,...,17.0,44.7,3.0,2.0,1.0,0.0,33.3,Matches,2022,Manchester United
4,Nick Pope,eng ENG,GK,30.0,37,37,3261,36.2,32.0,0.88,...,14.0,37.8,5.0,2.0,2.0,1.0,50.0,Matches,2022,Newcastle United

In [18]:
all_matches_df2.reset_index(drop=True, inplace=True)  # Reset the index to provide automatic numbering
all_matches_df2.to_csv('Goalkeepers.csv')  # Save to CSV